spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE:scboard}
    username: ${MYSQL_USER:scboard}
    password: ${MYSQL_PASSWORD:dev-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  docker:
    compose:
      enabled: true
      file: compose.yaml
      lifecycle-management: start-and-stop
  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: debug
